### ISSUE TITLE
Padding code in commit ede2cff5146a55ff7aed12d0751f99c05f5ba91b

### ISSUE THREAD

**Issue by sagamusix** [KKQ-KKQ/sf2convert#3]
I had a look at the commit adding support for >2GB files, and the newly added code for padding in commit ede2cff5146a55ff7aed12d0751f99c05f5ba91b caught my eye. Looking at the code, it seems like the padding byte is skipped *before* reading the chunk, not afterwards. For example, if the length field right after the initial `RIFF` was odd-sized, one byte after the `sfbk` signature would be skipped. However, the padding byte should be at the end.

Also, if this code is used for both SF2 and SF3 reading, it will have to ignore the padding in case of the sample chunk, because currently padding is written if the FLAC or Vorbis data happens to have an odd size, and it seems like this was already accepted as the status quo: https://github.com/FluidSynth/fluidsynth/wiki/SoundFont3Format

**Comment by KKQ-KKQ** [comment]
That code will work properly before reading the chunk.

RIFF format demands FourCC must be in even bytes. Because of that the code is added.
I didn't know the site. I consider it. Thanks.

**Comment by sagamusix** [comment]
Sorry for the delay. What I mean is the following. Let's assume that the length field right after the `RIFF` magic bytes is odd. Next thing the code does is verify that the magic bytes `sfbk` follow, which will be true. However, with the new code, the next thing it will do is skip one byte, and **then** verify if the next four bytes are `LIST`, which will be false because we skipped the `L`. It should call `skip` **after** reading the chunk, not before reading it. The same applies for sub chunks. The `skip` call needs to be at the end of the loop, not at the start, because the padding byte comes after the chunk whose size was odd.

**Comment by KKQ-KKQ** [comment]
FourCC must be even. A pad byte is inserted when chunk's length is not even.
[https://en.wikipedia.org/wiki/Resource_Interchange_File_Format](https://en.wikipedia.org/wiki/Resource_Interchange_File_Format)
> a pad byte, if the chunk's length is not even.

**Comment by KKQ-KKQ** [comment]
RIFF is even, a length field is even, LIST is even, a length field is even, FourCC is even, a chunk is even or odd, and a pad when the chunk is odd.
All are even.

But the code has already fixed. I considered SF3 format and no padding inserted.

**Comment by sagamusix** [comment]
I'm fully aware that all official SF2 chunks are even-sized, but as you point out yourself, a fully compliant RIFF parser must be able to handle odd-sized chunks. The point is that the padding byte of odd-sized chunks is at the *end* of the chunk, not at the *start*. I read your code again and it expects the padding byte to be at the start.

Here's a (hand-made, but still valid) SF2 file demonstrating this issue: [Saron.zip](https://github.com/KKQ-KKQ/sf2convert/files/7165491/Saron.zip)

Just for demonstrating the problem, the RIFF size is odd. sf2convert 2.0.5 will bail out early because it will try to read a padding byte before the first `LIST` chunk, which is wrong. The padding byte always follows at the end of chunks. Other SF2 parsers don't have this issue.

You could of course simply remove the padding code again for the reasons you provided above (it shouldn't be necessary in real-world files). But the way it's currently written, it will misbehave once an odd-sized chunk (which is not the SF3 sample chunk) is found in a file, maybe because some SF2 authoring tool decided to write some additional RIFF chunks which are not officially part of the SF2 specifications, but should be allowed nevertheless because SF2 is otherwise a valid RIFF container.

**Comment by KKQ-KKQ** [comment]
There is a bug when the final chunk is odd.
I will fix it. Thanks.

**Comment by KKQ-KKQ** [comment]
I have fixed it. Please check it out. It should be OK.

**Comment by KKQ-KKQ** [comment]
I didn't remove the code because SF2 INFO LIST chunk can be odd.

**Comment by KKQ-KKQ** [comment]
I tried to open Saron.SF2 in Polyphone but I cannot. Invalid SF2.

**Comment by sagamusix** [comment]
Sorry, forgot to report back here. All is good now!
